import jsPDF from "jspdf";

export function exportCasePdf(caseData: any, report: any) {
  const doc = new jsPDF();

  const patient = caseData.patient || {};
  const history = caseData.history || {};
  const exam = caseData.physicalExam || {};
  const diagnostics = caseData.diagnostics || {};

  let y = 20;

  const addTitle = (text: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text(text, 15, y);
    y += 12;
  };

  const addHeading = (text: string) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(text, 15, y);
    y += 8;
  };

  const addLine = (label: string, value: any) => {
    if (!value) return;

    if (Array.isArray(value) && value.length === 0) return;

    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    const text =
      Array.isArray(value)
        ? value.join(", ")
        : String(value);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const lines = doc.splitTextToSize(
      `${label}: ${text}`,
      180
    );

    doc.text(lines, 15, y);
    y += lines.length * 6;
  };

  addTitle("VetDx Assist");
  addLine("Generated", new Date().toLocaleString());

  addHeading("Patient Information");

  addLine("Species", patient.species);
  addLine("Breed", patient.breed);
  addLine("Age", patient.age);
  addLine("Sex", patient.sex);
  addLine("Weight", patient.weight);

  addHeading("Clinical History");

  addLine("Chief Complaint", history.chiefComplaint);
  addLine("Duration", history.duration);
  addLine("Illness History", history.illnessHistory);
  addLine("Previous Treatment", history.previousTreatment);

  addHeading("Physical Examination");

  Object.entries(exam).forEach(([key, value]) => {
    addLine(key, value);
  });

  addHeading("Diagnostics");

  Object.entries(diagnostics).forEach(([key, value]) => {
    addLine(key, value);
  });

  addHeading("AI Clinical Summary");

  addLine(
    "Summary",
    report.clientSummary || report.summary
  );

  if (
    Array.isArray(report.problemList) &&
    report.problemList.length
  ) {
    addHeading("Problem List");

    report.problemList.forEach((item: any) =>
      addLine("•", item)
    );
  }

  if (
    Array.isArray(report.differentials) &&
    report.differentials.length
  ) {
    addHeading("Top Differentials");

    report.differentials.forEach((d: any, i: number) => {
      addLine(`${i + 1}`, d.name);
    });
  }

  if (
    Array.isArray(report.recommendedDiagnostics)
  ) {
    addHeading("Recommended Diagnostics");

    report.recommendedDiagnostics.forEach((item: any) =>
      addLine("•", item)
    );
  }

  if (
    Array.isArray(report.treatmentConsiderations)
  ) {
    addHeading("Treatment Considerations");

    report.treatmentConsiderations.forEach((item: any) =>
      addLine("•", item)
    );
  }

  if (
    Array.isArray(report.monitoring)
  ) {
    addHeading("Monitoring");

    report.monitoring.forEach((item: any) =>
      addLine("•", item)
    );
  }

  if (
    Array.isArray(report.clinicalPearls)
  ) {
    addHeading("Clinical Pearls");

    report.clinicalPearls.forEach((item: any) =>
      addLine("•", item)
    );
  }

  y += 10;

  doc.setFontSize(9);

  doc.text(
    "Generated by VetDx Assist • AI-assisted clinical decision support",
    15,
    y
  );

  doc.save(
    `VetDx_Case_${new Date().getTime()}.pdf`
  );
}